<?php

namespace App\Traits;

use \Ramsey\Uuid\Uuid as RamseyUuid;

trait Uuid
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->incrementing = false;
            $model->keyType = 'string';
            $model->{$model->getKeyName()} = RamseyUuid::uuid4();
        });
    }
}
