version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
  local:
    external:
      name: ${NETWORKS_EXTERNAL}

services:

#  ### Artisan ################################################
#  artisan:
#    image: resolutte/php-fpm-${PHP_VERSION}
#    container_name: resolutte-artisan
#    environment:
#      PHP_VERSION: ${PHP_VERSION}
#    volumes:
#      - ${APP_CODE_PATH_HOST}${APP_NAME}:${APP_CODE_PATH_CONTAINER}${APP_CONTAINER_FLAG}
#    working_dir: ${APP_CODE_PATH_CONTAINER}
#    entrypoint: ['${APP_CODE_PATH_CONTAINER}/artisan']
#    user: "${PHP_FPM_PUID}:${PHP_FPM_PGID}"
#    networks:
#      - backend
#
#  ### Composer ################################################
#  composer:
#    image: composer:latest
#    container_name: resolutte-composer
#    tty: true
#    volumes:
#      - ${APP_CODE_PATH_HOST}${APP_NAME}:${APP_CODE_PATH_CONTAINER}${APP_CONTAINER_FLAG}
#    working_dir: ${APP_CODE_PATH_CONTAINER}
#    entrypoint: "composer --ignore-platform-reqs"
#    user: "${PHP_FPM_PUID}:${PHP_FPM_PGID}"
#    networks:
#      - backend
#
#  ### Npm ################################################
#  npm:
#    image: node:12
#    container_name: resolutte-npm
#    ports:
#      - "${BROWSERSYNC_PORT}:3000"
#      - "${BROWSERSYNC_ADMIN_PORT}:3001"
#      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
#    environment:
#      MIX_MODE: ${MIX_MODE}
#      MIX_BROWSERSYNC: ${MIX_BROWSERSYNC}
#    entrypoint: "npm run ${MIX_MODE}"
#    volumes:
#      - ./:/var/www
#      - ./.docker/nginx/keys:/etc/ssl
#    working_dir: /var/www
#    user: "${PHP_FPM_PUID}:${PHP_FPM_PGID}"
#    networks:
#      - backend

  ### PHP-FPM ###############################################
  app:
    image: resolutte-app
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        # DEV
        - INSTALL_SUBVERSION=${PHP_FPM_INSTALL_SUBVERSION}
        - NVM_NODEJS_ORG_MIRROR=${PHP_FPM_NVM_NODEJS_ORG_MIRROR}
        - INSTALL_NODE=${PHP_FPM_INSTALL_NODE}
        - NPM_REGISTRY=${PHP_FPM_NPM_REGISTRY}
        - INSTALL_YARN=${PHP_FPM_INSTALL_YARN}
        - INSTALL_NPM_GULP=${PHP_FPM_INSTALL_NPM_GULP}
        - INSTALL_NPM_BOWER=${PHP_FPM_INSTALL_NPM_BOWER}
        - INSTALL_NPM_VUE_CLI=${PHP_FPM_INSTALL_NPM_VUE_CLI}
        - INSTALL_NPM_ANGULAR_CLI=${PHP_FPM_INSTALL_NPM_ANGULAR_CLI}
        - INSTALL_DRUSH=${PHP_FPM_INSTALL_DRUSH}
        - INSTALL_WP_CLI=${PHP_FPM_INSTALL_WP_CLI}
        - INSTALL_DRUPAL_CONSOLE=${PHP_FPM_INSTALL_DRUPAL_CONSOLE}
        - INSTALL_V8JS=${PHP_FPM_INSTALL_V8JS}
        - DOCKERIZE_INSTALL=${PHP_FPM_DOCKERIZE_INSTALL}
        - COMPOSER_INSTALL=${PHP_FPM_COMPOSER_INSTALL}
        - INSTALL_PHP_FPM_SSH=${PHP_FPM_INSTALL_SSH}
        - INSTALL_LARAVEL_ENVOY=${PHP_FPM_INSTALL_LARAVEL_ENVOY}
        - INSTALL_LARAVEL_INSTALLER=${PHP_FPM_INSTALL_LARAVEL_INSTALLER}
        - INSTALL_DEPLOYER=${PHP_FPM_INSTALL_DEPLOYER}
        - INSTALL_PRESTISSIMO=${PHP_FPM_INSTALL_PRESTISSIMO}
        - INSTALL_MC=${PHP_FPM_INSTALL_MC_MINIO}
        - INSTALL_SYMFONY=${PHP_FPM_INSTALL_SYMFONY}
        - INSTALL_PYTHON=${PHP_FPM_INSTALL_PYTHON}
        - INSTALL_TERRAFORM=${PHP_FPM_INSTALL_TERRAFORM}
        - INSTALL_DUSK_DEPS=${PHP_FPM_INSTALL_DUSK_DEPS}
        - INSTALL_LIBPNG=${PHP_FPM_INSTALL_LIBPNG}
        - INSTALL_INOTIFY=${PHP_FPM_INSTALL_INOTIFY}
        - INSTALL_FSWATCH=${PHP_FPM_INSTALL_FSWATCH}
        - INSTALL_AST=${PHP_FPM_INSTALL_AST}
        - CHROME_DRIVER_VERSION=${PHP_FPM_CHROME_DRIVER_VERSION}
        - NODE_VERSION=${PHP_FPM_NODE_VERSION}
        - YARN_VERSION=${PHP_FPM_YARN_VERSION}
        - DRUSH_VERSION=${PHP_FPM_DRUSH_VERSION}
        - INSTALL_POWERLINE=${PHP_FPM_INSTALL_POWERLINE}
        - INSTALL_SUPERVISOR=${PHP_FPM_INSTALL_SUPERVISOR}
        - INSTALL_GNU_PARALLEL=${PHP_FPM_INSTALL_GNU_PARALLEL}
        # PROD
        - DF_PHP_VERSION=${PHP_VERSION}
        - DF_PHALCON_VERSION=${PHALCON_VERSION}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_PCOV=${PHP_FPM_INSTALL_PCOV}
        - INSTALL_PHPDBG=${PHP_FPM_INSTALL_PHPDBG}
        - PHP_FPM_INSTALL_BLACKFIRE=${PHP_FPM_INSTALL_BLACKFIRE}
        - INSTALL_SSH2=${PHP_FPM_INSTALL_SSH2}
        - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
        - INSTALL_XSL=${PHP_FPM_INSTALL_XSL}
        - INSTALL_SMB=${PHP_FPM_INSTALL_SMB}
        - INSTALL_IMAP=${PHP_FPM_INSTALL_IMAP}
        - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
        - INSTALL_AMQP=${PHP_FPM_INSTALL_AMQP}
        - INSTALL_CASSANDRA=${PHP_FPM_INSTALL_CASSANDRA}
        - INSTALL_GEARMAN=${PHP_FPM_INSTALL_GEARMAN}
        - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_GMP=${PHP_FPM_INSTALL_GMP}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
        - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE}
        - INSTALL_OCI8=${PHP_FPM_INSTALL_OCI8}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
        - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
        - INSTALL_POSTGIS=${PHP_FPM_INSTALL_POSTGIS}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
        - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
        - INSTALL_PHALCON=${PHP_FPM_INSTALL_PHALCON}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - INSTALL_TAINT=${PHP_FPM_INSTALL_TAINT}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
        - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
        - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
        - INSTALL_FAKETIME=${PHP_FPM_INSTALL_FAKETIME}
        - INSTALL_IONCUBE=${PHP_FPM_INSTALL_IONCUBE}
        - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
        - INSTALL_CACHETOOL=${PHP_FPM_INSTALL_CACHETOOL}
        - INSTALL_YAML=${PHP_FPM_INSTALL_YAML}
        - INSTALL_RDKAFKA=${PHP_FPM_INSTALL_RDKAFKA}
        - INSTALL_GETTEXT=${PHP_FPM_INSTALL_GETTEXT}
        - INSTALL_ADDITIONAL_LOCALES=${PHP_FPM_INSTALL_ADDITIONAL_LOCALES}
        - INSTALL_MYSQL_CLIENT=${PHP_FPM_INSTALL_MYSQL_CLIENT}
        - INSTALL_PING=${PHP_FPM_INSTALL_PING}
        - INSTALL_SSHPASS=${PHP_FPM_INSTALL_SSHPASS}
        - INSTALL_MAILPARSE=${PHP_FPM_INSTALL_MAILPARSE}
        - INSTALL_PCNTL=${PHP_FPM_INSTALL_PCNTL}
        - ADDITIONAL_LOCALES=${PHP_FPM_ADDITIONAL_LOCALES}
        - INSTALL_FFMPEG=${PHP_FPM_FFMPEG}
        - INSTALL_XHPROF=${PHP_FPM_INSTALL_XHPROF}
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
        - LOCALE=${PHP_FPM_DEFAULT_LOCALE}
        - TZ=${PHP_FPM_TIMEZONE}
        - http_proxy
        - https_proxy
        - no_proxy
        - PHP_FPM_EXPOSE_PORT=9000
    volumes:
      - .docker/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      #- .docker/php-fpm/entrypoint.sh:${APP_CODE_PATH_CONTAINER}/entrypoint.sh
      - ${APP_CODE_PATH_HOST}${APP_NAME}:${APP_CODE_PATH_CONTAINER}${APP_CONTAINER_FLAG}
    ports:
      - "${PHP_FPM_SSH_PORT_7}:22"
    tty: true
    #    depends_on:
    #      - mysql
    #      - mongo
    #      - redis
    expose:
      - "9000"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - FAKETIME=${PHP_FPM_FAKETIME}
    networks:
      - local
      - backend
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s ./entrypoint.sh
    #entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s

  ### NGINX Server #########################################
  nginx:
    image: resolutte-nginx
    container_name: nginx
    restart: always
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${APP_CODE_PATH_HOST}${APP_NAME}:${APP_CODE_PATH_CONTAINER}${APP_CONTAINER_FLAG}
    ports:
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "${NGINX_HOST_HTTP_PORT}:80"
    depends_on:
      - app
    networks:
      - local
      - frontend
      - backend

#  ### Laravel Worker ############################################
#  laravel-worker:
#    image: resolutte-laravel-worker
#    container_name: laravel-worker
#    restart: always
#    build:
#      context: ./
#      dockerfile: .docker/laravel-worker/Dockerfile
#      args:
#        - PHP_VERSION=${PHP_VERSION}
#        - PHALCON_VERSION=${PHALCON_VERSION}
#        - INSTALL_PGSQL=${PHP_WORKER_INSTALL_PGSQL}
#        - INSTALL_BCMATH=${PHP_WORKER_INSTALL_BCMATH}
#        - INSTALL_PHALCON=${PHP_WORKER_INSTALL_PHALCON}
#        - INSTALL_SOAP=${PHP_WORKER_INSTALL_SOAP}
#        - INSTALL_ZIP_ARCHIVE=${PHP_WORKER_INSTALL_ZIP_ARCHIVE}
#        - INSTALL_MYSQL_CLIENT=${PHP_WORKER_INSTALL_MYSQL_CLIENT}
#        - INSTALL_AMQP=${PHP_WORKER_INSTALL_AMQP}
#        - INSTALL_CASSANDRA=${PHP_WORKER_INSTALL_CASSANDRA}
#        - INSTALL_GEARMAN=${PHP_WORKER_INSTALL_GEARMAN}
#        - INSTALL_GHOSTSCRIPT=${PHP_WORKER_INSTALL_GHOSTSCRIPT}
#        - INSTALL_SWOOLE=${PHP_WORKER_INSTALL_SWOOLE}
#        - INSTALL_TAINT=${PHP_WORKER_INSTALL_TAINT}
#        - INSTALL_FFMPEG=${PHP_WORKER_INSTALL_FFMPEG}
#        - INSTALL_GMP=${PHP_WORKER_INSTALL_GMP}
#        - INSTALL_REDIS=${PHP_WORKER_INSTALL_REDIS}
#        - PUID=${PHP_WORKER_PUID}
#        - PGID=${PHP_WORKER_PGID}
#    volumes:
#      - ${APP_CODE_PATH_HOST}${APP_NAME}:${APP_CODE_PATH_CONTAINER}${APP_CONTAINER_FLAG}
#      - .docker/laravel-worker/supervisord.d:/etc/supervisord.d
#    depends_on:
#      - app
#    networks:
#      - local
#      - backend
#
#  ### Laravel Horizon ############################################
#  laravel-horizon:
#    image: resolutte-laravel-horizon
#    container_name: laravel-horizon
#    restart: always
#    build:
#      context: ./
#      dockerfile: .docker/laravel-horizon/Dockerfile
#      args:
#        - PHP_VERSION=${PHP_VERSION}
#        - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
#        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
#        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
#        - INSTALL_SOCKETS=${LARAVEL_HORIZON_INSTALL_SOCKETS}
#        - INSTALL_CASSANDRA=${PHP_FPM_INSTALL_CASSANDRA}
#        - INSTALL_PHPREDIS=${LARAVEL_HORIZON_INSTALL_PHPREDIS}
#        - INSTALL_MONGO=${LARAVEL_HORIZON_INSTALL_MONGO}
#    volumes:
#      - ${APP_CODE_PATH_HOST}${APP_NAME}:${APP_CODE_PATH_CONTAINER}${APP_CONTAINER_FLAG}
#      - .docker/laravel-horizon/supervisord.d:/etc/supervisord.d
#    depends_on:
#      - app
#    networks:
#      - local
#      - backend